### PR TITLE
@miniTicker - markets.lower() not worked

### PR DESCRIPTION
**Pull request by DaWe35**
Some lines was a bit confused, if (never) removed

### CODE REVIEW

**Comment by bithon** [comment]
I see, the `if market == "!userData":` makes it impossible to match the if clause you removed.
Its late, i would like to make some tests before i merge, this part of code is very sensible and must be tested very well. will do it after this weekend! thanks and best regards!

**Comment by DaWe35** [comment]
Commit 1+2: markets.lower working with miniticker (I tested, but maybe need more tests)
Commit 3+4+5: create_stream prints a warning, if URI > 8004. Please check if it is good.

**Comment by bithon** [comment]
Thanks for the update.
In general the API doesnt use print for errors. Its done by logging itself. the coder can decide to print to stdout or to stream the log msg to a file.
I also suggest to use the loglevel debug or info instead of critical. The method already returns `False` since your update, so if the coder makes a clean implementation, this should not be critical or an error anymore... i personaly want to keep my logfiles as small as possible. If we log this even if the coder cares with catching False, the logfile gets bloated for no reason... 

I dont know if you know :) but you can see what the status of your stream is:
```
stream_info = self.get_stream_info(stream_id)
stream_info['status']
```
i am going to make the tests for the first commit tomorrow, 

best regards,
oliver

**Comment by DaWe35** [comment]
Hmm. I don't know, what is the best solution, but if a crazy user (me) tries to connect to 500 channels, we need to warn he about the 8004 limit, because he's not sure he knows why it doesn't work (and maybe he will create an issue on Github XD)

**Comment by bithon** [comment]
its true, at the moment it is an error, but its catch able so critical is to high.

**Comment by DaWe35** [comment]
Ahh sorry, I just understood what !miniTicker does. I hope I've fixed the error, please check it out :)

**Pull request merged**
